# Generated by Django 4.2.23 on 2025-06-15 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('business_type', models.CharField(choices=[('restaurant', 'Ресторан/Кафе'), ('shop', 'Магазин/E-commerce'), ('service', 'Послуги'), ('portfolio', 'Портфоліо'), ('blog', 'Блог/Новини'), ('corporate', 'Корпоративний сайт'), ('other', 'Інше')], max_length=50, verbose_name='Тип бізнесу')),
                ('site_type', models.CharField(choices=[('landing', 'Лендінг (1 сторінка)'), ('multi_page', 'Багатосторінковий сайт'), ('ecommerce', 'Інтернет-магазин'), ('web_app', 'Веб-додаток')], max_length=50, verbose_name='Тип сайту')),
                ('design_complexity', models.CharField(choices=[('simple', 'Простий дизайн'), ('medium', 'Середній дизайн'), ('complex', 'Складний дизайн'), ('custom', 'Унікальний дизайн')], max_length=30, verbose_name='Складність дизайну')),
                ('features', models.JSONField(default=list, verbose_name='Додаткові функції')),
                ('has_content', models.BooleanField(default=False, verbose_name='Є готовий контент')),
                ('timeline', models.CharField(choices=[('asap', 'Якомога швидше'), ('week', 'Протягом тижня'), ('month', 'Протягом місяця'), ('flexible', 'Гнучкі терміни')], max_length=30, verbose_name='Терміни')),
                ('budget_range', models.CharField(choices=[('under_200', 'До $200'), ('200_500', '$200-500'), ('500_1000', '$500-1000'), ('1000_plus', '$1000+')], max_length=30, verbose_name='Бюджет')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розрахункова ціна')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Результат опитувальника',
                'verbose_name_plural': 'Результати опитувальника',
            },
        ),
    ]
