# Generated by Django 4.2.23 on 2025-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='design_complexity',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='features',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='has_content',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='site_type',
        ),
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='timeline',
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='business_sphere',
            field=models.CharField(choices=[('goods', 'Товари (інтернет-магазин, каталог)'), ('services', 'Послуги (клініка, салон, студія)'), ('education', 'Освіта / онлайн-курси'), ('personal_brand', 'Особистий бренд'), ('startup', 'Стартап / ІТ продукт')], default='services', max_length=50, verbose_name='Сфера бізнесу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='estimated_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Терміни (дні)'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='functionality',
            field=models.TextField(blank=True, verbose_name='Рекомендований функціонал'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='integrations',
            field=models.TextField(blank=True, verbose_name='Рекомендовані інтеграції'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='main_goal',
            field=models.CharField(choices=[('sales', 'Продажі / заявки'), ('presentation', 'Презентація бізнесу'), ('blog_expertise', 'Блог + експертність'), ('landing_ads', 'Лендінг під рекламу')], default='services', max_length=50, verbose_name='Головна мета сайту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='needed_features',
            field=models.JSONField(default=list, verbose_name='Потрібні функції'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='priorities',
            field=models.JSONField(default=list, verbose_name='Що найважливіше'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='style',
            field=models.TextField(blank=True, verbose_name='Стиль сайту'),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='traffic_sources',
            field=models.JSONField(default=list, verbose_name='Джерела трафіку'),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Загальні рекомендації'),
        ),
    ]
