# Generated by Django 4.2.23 on 2025-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_questionnaireresult_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresult',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Ім'я"),
        ),
    ]
